/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
//上面再銃啥小???????????????


//convert  weatherText to Skycons
var drawSkycons = function(id,weather){
  console.log(id + ": "+weather);
  if(weather === "Cloudy"){
      skycons.set(id, Skycons.CLOUDY);
    }else if (weather === "Sunny"){
      skycons.set(id, Skycons.CLEAR_DAY);
    }else if(weather === "Rain" || weather === "Thunderstorms" || weather === "Showers"){
      skycons.set(id, Skycons.RAIN);
    }else if(weather === "Fog"){
      skycons.set(id, Skycons.FOG);
    }else if(weather === "Wind"){
      skycons.set(id, Skycons.WIND);
    };  
};


//inititalQuery
var initialQuery = function(){
  //get the local code
  $("ul li").each(  function(){
    var data =$(this).attr("data");
    var src = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20%3D%20" +data +  "%20and%20u%3D%22c%22&format=json&diagnostics=true&callback=";
    var $currObj = $(this);
  
    //get JSON
    $.getJSON(src,function(data){
      var temp = data.query.results.channel.item.condition.temp;
      $currObj.find("#temperature").html(temp +  "&#8451;");
    }
    );  
  }  
  );
};

// interaction to the dropdown
$("ul li ").click(function(){
  console.log("fuck you friend la");
  var data =$(this).attr("data");
  var src = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20%3D%20" +data +  "%20and%20u%3D%22c%22&format=json&diagnostics=true&callback=";

  $.getJSON(src,function(data){
    console.log(data);
    var currTemp = data.query.results.channel.item.condition.temp;   
    var foreTmep1 = data.query.results.channel.item.forecast[0].low +" - "+data.query.results.channel.item.forecast[0].high;
    var foreTemp2 = data.query.results.channel.item.forecast[1].low +" - "+data.query.results.channel.item.forecast[1].high;
    var foreTemp3 = data.query.results.channel.item.forecast[2].low +" - "+data.query.results.channel.item.forecast[2].high;
    var currDate = data.query.results.channel.item.forecast[0].date;
    var foreDate2 = data.query.results.channel.item.forecast[1].date;
    var foreDate3 = data.query.results.channel.item.forecast[2].date;
    var currText = data.query.results.channel.item.condition.text;
    var foreText1 = data.query.results.channel.item.forecast[0].text;
    var foreText2 = data.query.results.channel.item.forecast[1].text;
    var foreText3 = data.query.results.channel.item.forecast[2].text; 
    var currDay = data.query.results.channel.item.forecast[0].day;

    $(".temperature").html(currTemp);
    $(".condition").html(": "+ currText);
    $(".date").html(currDate);
    $(".Date").html("It's fucking" + currDate);
    $(".foreDate th:nth-child(1)").html(currDate);
    $(".foreDate th:nth-child(2)").html(foreDate2);
    $(".foreDate th:nth-child(3)").html(foreDate3);
    $(".foreTemp td:nth-child(1)").html(foreTmep1 + "&#8451;");
    $(".foreTemp td:nth-child(2)").html(foreTemp2 + "&#8451;");
    $(".foreTemp td:nth-child(3)").html(foreTemp3 + "&#8451;");

    drawSkycons("today",currText);
    drawSkycons("day1",foreText1);
    drawSkycons("day2",foreText2);
    drawSkycons("day3",foreText3);
  }
  );    

}
);


var firstQuery = function(){
  console.log("fuck you Taipei City");
  var data ="2306179";
  var src = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20%3D%20" +data +  "%20and%20u%3D%22c%22&format=json&diagnostics=true&callback=";

  $.getJSON(src,function(data){
    console.log(data);
    var currTemp = data.query.results.channel.item.condition.temp;
    var foreTmep1 = data.query.results.channel.item.forecast[0].low +" - "+data.query.results.channel.item.forecast[0].high;
    var foreTemp2 = data.query.results.channel.item.forecast[1].low +" - "+data.query.results.channel.item.forecast[1].high;
    var foreTemp3 = data.query.results.channel.item.forecast[2].low +" - "+data.query.results.channel.item.forecast[2].high;
    var currDate = data.query.results.channel.item.forecast[0].date;
    var foreDate2 = data.query.results.channel.item.forecast[1].date;
    var foreDate3 = data.query.results.channel.item.forecast[2].date;
    var currText = data.query.results.channel.item.condition.text;
    var foreText1 = data.query.results.channel.item.forecast[0].text;
    var foreText2 = data.query.results.channel.item.forecast[1].text;
    var foreText3 = data.query.results.channel.item.forecast[2].text; 
    var currDay = data.query.results.channel.item.forecast[0].day;
    console.log(currDate);
    $(".temperature").html(currTemp);
    $(".condition").html(": "+ currText);
    $(".date").html(currDate);
    $(".Date").html("It's fucking" + currDate);
    $(".foreDate th:nth-child(1)").html(currDate);
    $(".foreDate th:nth-child(2)").html(foreDate2);
    $(".foreDate th:nth-child(3)").html(foreDate3);
    $(".foreTemp td:nth-child(1)").html(foreTmep1 + "&#8451;");
    $(".foreTemp td:nth-child(2)").html(foreTemp2 + "&#8451;");
    $(".foreTemp td:nth-child(3)").html(foreTemp3 + "&#8451;");
    drawSkycons("today",currText);
    drawSkycons("day1",foreText1);
    drawSkycons("day2",foreText2);
    drawSkycons("day3",foreText3);
  });    

};


firstQuery();
initialQuery();

